language: python
sudo: false
env:
  # All currently supported versions of Django / Python
  # except Python 3.2 (since Jinja doesn't support it)
  # https://docs.djangoproject.com/en/dev/faq/install/#what-python-version-can-i-use-with-django

  - TOXENV=py25-dj1.4
  - TOXENV=py26-dj1.4
  - TOXENV=py27-dj1.4

  - TOXENV=py27-dj1.7
  - TOXENV=py33-dj1.7
  - TOXENV=py34-dj1.7

  - TOXENV=py27-dj1.8
  - TOXENV=py33-dj1.8
  - TOXENV=py34-dj1.8

install:
  - pip install tox
script:
  - tox -v -- -v
